### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by hunkim** [hunkim/word-rnn-tensorflow#19]
Cannot reproduce it anymore, but for the record:

```bash
hunkim:~/word-rnn-tensorflow$ python sample.py --prime="kmalloc"
kmalloc
Traceback (most recent call last):
  File "sample.py", line 42, in <module>
    main()
  File "sample.py", line 25, in main
    sample(args)
  File "sample.py", line 39, in sample
    print(model.sample(sess, words, vocab, args.n, args.prime, args.sample))
  File "/home/hunkim/word-rnn-tensorflow/model.py", line 97, in sample
    pred = words[sample]
IndexError: list index out of range
```

**Comment by mperiwal-kore** [comment]
I am getting this error a lot of times.

**Comment by sunxiaobiu** [comment]
Could there be something wrong with the format of the lines in the words_vocab.pkl file?like empty lines?

**Comment by hunkim** [comment]
@sunxiaobiu Could you reproduce this error?

**Comment by suzil** [comment]
I get the error, but for the line with the error when I setup a `try: [line] except IndexError: import pdb; pdb.set_trace()` I never again encounter the error.
