### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by joe-rivera** [hunkim/word-rnn-tensorflow#4]
Getting the following when running on OS X, Python 2.7.10. Any ideas?

Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from model import Model
  File "/word-rnn-tensorflow-master/model.py", line 2, in <module>
    from tensorflow.models.rnn import rnn_cell
  File "/tensorflow/lib/python2.7/site-packages/tensorflow/models/rnn/rnn_cell.py", line 21, in <module>
    raise ImportError("This module is deprecated.  Use tf.nn.rnn_cell instead.")
ImportError: This module is deprecated.  Use tf.nn.rnn_cell instead.

**Comment by hunkim** [comment]
Yes. We were aware of this issue. If you can fix it, please send us patch.

Sung

**Comment by amw5g** [comment]
I don't know how to send a patch, but I was able to find a fix from https://github.com/tensorflow/tensorflow/issues/2685
```python
import tensorflow as tf
#from tensorflow.models.rnn import tf.nn.rnn_cell
#from tensorflow.models.rnn import seq2seq

import numpy as np

class Model():
    def __init__(self, args, infer=False):
        self.args = args
        if infer:
            args.batch_size = 1
            args.seq_length = 1

        if args.model == 'rnn':
            cell_fn = tf.nn.rnn_cell.BasicRNNCell #changed
        elif args.model == 'gru':
            cell_fn = tf.nn.rnn_cell..GRUCell #changed
        elif args.model == 'lstm':
            cell_fn = tf.nn.rnn_cell.BasicLSTMCell #changed
        else:
            raise Exception("model type not supported: {}".format(args.model))

        cell = cell_fn(args.rnn_size)

        self.cell = cell = tf.nn.rnn_cell.MultiRNNCell([cell] * args.num_layers) #changed

        self.input_data = tf.placeholder(tf.int32, [args.batch_size, args.seq_length])
        self.targets = tf.placeholder(tf.int32, [args.batch_size, args.seq_length])
        self.initial_state = cell.zero_state(args.batch_size, tf.float32)

        with tf.variable_scope('rnnlm'):
            softmax_w = tf.get_variable("softmax_w", [args.rnn_size, args.vocab_size])
            softmax_b = tf.get_variable("softmax_b", [args.vocab_size])
            with tf.device("/cpu:0"):
                embedding = tf.get_variable("embedding", [args.vocab_size, args.rnn_size])
                inputs = tf.split(1, args.seq_length, tf.nn.embedding_lookup(embedding, self.input_data))
                inputs = [tf.squeeze(input_, [1]) for input_ in inputs]

        def loop(prev, _):
            prev = tf.matmul(prev, softmax_w) + softmax_b
            prev_symbol = tf.stop_gradient(tf.argmax(prev, 1))
            return tf.nn.embedding_lookup(embedding, prev_symbol)

        outputs, last_state = tf.nn.seq2seq.rnn_decoder(inputs, self.initial_state, cell, loop_function=loop if infer else None, scope='rnnlm') #changed
        output = tf.reshape(tf.concat(1, outputs), [-1, args.rnn_size])
        self.logits = tf.matmul(output, softmax_w) + softmax_b
        self.probs = tf.nn.softmax(self.logits)
        loss = tf.nn.seq2seq.sequence_loss_by_example([self.logits], #changed
                [tf.reshape(self.targets, [-1])],
                [tf.ones([args.batch_size * args.seq_length])],
                args.vocab_size)
...
```

**Comment by yosit** [comment]
https://github.com/hunkim/word-rnn-tensorflow/pull/5 fixes it

**Comment by hunkim** [comment]
#5 merged!
