### ISSUE TITLE
AttributeError: 'module' object has no attribute 'merge_all'

### ISSUE THREAD

**Issue by koctob** [hunkim/word-rnn-tensorflow#54]
#python3 train.py

reading text file
Traceback (most recent call last):
  File "train.py", line 134, in <module>
    main()
  File "train.py", line 52, in main
    train(args)
  File "train.py", line 88, in train
    merged = tf.summary.merge_all()
AttributeError: 'module' object has no attribute 'merge_all'

Running it I'm getting this error.
I've install tensor flow with : 
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp34-cp34m-linux_x86_64.whl

**Comment by koctob** [comment]
Sorry my fault the problem was related to tensorflow version and the python installation.
