### ISSUE TITLE
seq2seq can not import name

### ISSUE THREAD

**Issue by stevenochs2** [hunkim/word-rnn-tensorflow#59]
Hey, Thank you for this model. I'm a noob, trying to utilize this to push my thoughts on writing. I'd like to use this model to see what sort of word couplings it could produce to incorporate into my novel. Thanks for the help. 

I am getting this error. Using python 2.7 with Tensorflow 1.2 on mac - Sierra. 

Stevens-MacBook-Pro:char-rnn-tensorflow-master StevenOchs$ python train.py 
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from model import Model
  File "/Users/StevenOchs/Desktop/char-rnn-tensorflow-master/model.py", line 3, in <module>
    from tensorflow.contrib import legacy_seq2seq
ImportError: cannot import name legacy_seq2seq

Any thoughts?

**Comment by stevenochs2** [comment]
I solved this by creating a virtual environment and did a clean install there.
